### ISSUE TITLE
Not working on 2.1.10

### ISSUE THREAD

**Issue by kerlama** [magepal/magento2-preview-checkout-success-page#1]
Hi,

I manually installed it and after click on Checkout link , under Configuration I get this:

http://prntscr.com/hnf8y5

**Comment by srenon** [comment]
Can you try some of these recommendation https://stackoverflow.com/questions/32475892/reflectionexception-class-classname-does-not-exist-laravel

**Comment by kerlama** [comment]
Whats the point of going through all of this ? This is obviously extension problem.

**Comment by srenon** [comment]
60 installs in less than 30 days and only you have an issue https://packagist.org/packages/magepal/magento2-preview-checkout-success-page. 

So:

(1) Is this an extension or environment problem? 
(2) This particular code is part of all our extensions that have been downloaded over 65,000 times.

Please keep in mind that this is a free extension, so if spending 5 minutes out of your time is too much, then my time is not worth anything. Have a nice day.
