### ISSUE TITLE
Not working with Magento 2.3.3

### ISSUE THREAD

**Issue by fongd** [magepal/magento2-preview-checkout-success-page#2]
#### Magento version #:

2.3.3

#### Edition (EE, CE, OS, etc):

CE

#### Expected behavior:

Save Config & Preview or Save Config & Open New Window should display the order success page.

#### Actual behavior:

Instead of the order success page displaying, I get the "your cart is empty" page.

#### Steps to reproduce:

* Install the extension (I used composer 1.0.9)
* Configure this extension with a valid order number
* Enable the extension
* Click the Save Config & Open New Window button

#### Preconditions

Our site is available in English and French. Thinking it was related to this, I tried order IDs from either language of the store but get the same result.

**Comment by srenon** [comment]
@fongd ... I can not reproduce your issue on fresh install of 2.3.3

![image](https://user-images.githubusercontent.com/1415141/69446698-f9d8b700-0d22-11ea-8706-62e3a41fcec9.png)

**Comment by elfeffe** [comment]
I have the same problem using M2.3.4
It redirects me to my cart, empty if I had it empty, and with items if I added them.
I can't see other people's success page, instead, I see my cart with my session.

I use composer 1.0.9 version, but in admin it says 

Module Version: v1.0.0
Composer Version: v1.0.9

I don't know if it's related.

@fongd says they have English and French websites, we also have 2 websites (the real one and one that we use for ebay sales). Can it be related?

@srenon I can give you access to my store if you need

**Comment by srenon** [comment]
@elfeffe ... Are you trying to preview from the global or store level?

Can you double-check to see if it is creating the wrong store URL?

More than like the issue is caused by 
https://github.com/magepal/magento2-preview-checkout-success-page/blob/master/Block/Adminhtml/System/Config/Form/Field/Preview.php#L86

https://github.com/magepal/magento2-preview-checkout-success-page/blob/master/Block/Adminhtml/System/Config/Form/Field/Preview.php#L103

**Comment by poncho0193** [comment]
I cant install in magento 2.3.3 via composer, have the error:

[InvalidArgumentException]
  Package magepal/magento2-preview-checkout-success-page at version  has a PHP requirement incompatible with your PHP
   version (7.4.5)

**Comment by srenon** [comment]
Does Magento v2.3.3 support PHP 7.4.x?

https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by poncho0193** [comment]
ok i can install use the correct php version, but now have the error after install:

Deprecated Functionality: Function ReflectionType::__toString() is deprecated in /var/www/html/store/storecore/vendor/zendframework/zend-code/src/Reflection/ParameterReflection.php on line 84

i read is for php version but i don't know how refer to correct version, some idea?

**Comment by srenon** [comment]
Sorry, I have no idea without seeing the full error message. But I don't think this error message is coming from our extension. You should check what version of PHP your web server https://github.com/sebastianbergmann/phpunit/issues/3728
